CI: cancel old PR builds when new commits are pushed to a PR branch
JuliaTime/TimeZones.jl pull request #414
Opened 2022-11-08 20:00 UTC by DilumAluthge

2022-11-08 20:38 UTC, DilumAluthge commented
@omus Two CI jobs failed on Julia nightly with segfaults. Is this a known issue?

2022-11-08 23:55 UTC, DilumAluthge commented
Alright, after a retry, all jobs are passing.

@omus This is ready to review.

2022-11-12 03:25 UTC, DilumAluthge commented
Bump @omus

2022-11-25 17:53 UTC, omus commented
Sorry for the slow response. Looking at this now.

2022-11-25 18:11 UTC, omus requested changes
Overall I'm good with the concurrency suggestion. Just have a couple of minor suggestions.

2022-11-25 18:11 UTC, omus commented on .github/workflows/CI.yml
> +  # Cancel intermediate builds: only pull request builds
```suggestion
# Skip/cancel execution of queued/running jobs from outdated commits. Jobs run on the
# `master` branch are not subject to these restrictions and are always executed.
concurrency:
```

2022-11-25 18:11 UTC, omus commented on .github/workflows/CI.yml
> +  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
I can't think of a good reason not to cancel in progress jobs for branches and tags. Is there a scenario I'm not thinking of?
```suggestion
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
```

2022-11-26 22:46 UTC, omus approved these changes

2022-11-26 22:46 UTC, merged